// Formatting, matching pi-dash (its ultracite oxfmt preset, inlined so this repo has no extra dependency).
// oxfmt formats TS/JS/JSON/CSS; it does not format .astro files.
import { defineConfig } from "oxfmt";

export default defineConfig({
  arrowParens: "always",
  bracketSameLine: false,
  bracketSpacing: true,
  endOfLine: "lf",
  ignorePatterns: [
    "dist/**",
    ".astro/**",
    "node_modules/**",
    "public/**",
    "**/*.md",
    // generated by scripts/load-motion.ts (its --check compares the exact output)
    "src/styles/sections/load-motion.css",
  ],
  jsxSingleQuote: false,
  printWidth: 80,
  proseWrap: "never",
  quoteProps: "as-needed",
  semi: true,
  singleQuote: false,
  sortImports: { ignoreCase: true, newlinesBetween: true, order: "asc" },
  sortPackageJson: true,
  sortTailwindcss: { stylesheet: "./src/styles/global.css" },
  tabWidth: 2,
  trailingComma: "es5",
  useTabs: false,
});
